apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: "admin-api"
spec:
  targets:
  - name: mysql-apiserver
  peers:
  - mtls:
  origins:
  - jwt:
      # please see https://istio.io/help/ops/security/end-user-auth/
      issuer: ""
      jwksUri: ""
  principalBinding: USE_ORIGIN
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: admin-api
  namespace: default
spec:
  rules:
  - services: ["mysql-apiserver.default.svc.cluster.local"]
    paths: ["/admin/*"]
    methods: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: admin-api
  namespace: default
spec:
  subjects:
  - properties:
      request.auth.claims[email]: "s.miyoshi@example.com"
  roleRef:
    kind: ServiceRole
    name: "admin-api"
