apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: mysql-apiserver
  namespace: default
spec:
  rules:
  - services: ["mysql-apiserver.default.svc.cluster.local"]
    methods: ["GET", "POST"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: mysql-apiserver
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/sectest-frontend"
  - user: "cluster.local/ns/default/sa/sectest-mysql"
  roleRef:
    kind: ServiceRole
    name: "mysql-apiserver"
