apiVersion: v1
kind: Namespace
metadata:
  name: dangerarea
---
apiVersion: v1
kind: Pod
metadata:
  name: attacker
  namespace: dangerarea
spec:
  containers:
  - image: docker.io/smiyoshi/sectest-attacker:latest
    name: attacker
    command:
      - sleep
      - "3600"
  hostNetwork: true
