apiVersion: v1
kind: ServiceAccount
metadata:
  name: sectest-mysql-apiserver
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-apiserver
  namespace: default
  labels:
    app: mysql-apiserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-apiserver
    spec:
      serviceAccountName: sectest-mysql-apiserver
      containers:
        - name: mysql-apiserver
          image: docker.io/smiyoshi/sectest-apiserver:latest
          #        imagePullPolicy: Always
          env:
            - name: MYSQL_ADDR
              value: mysql.default.svc.cluster.local
          ports:
            - name: http
              containerPort: 4567
            - name: adminapi
              containerPort: 9000
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-apiserver
  labels:
    app: mysql-apiserver
  namespace: default
spec:
  ports:
    - name: http-user
      port: 4567
      targetPort: 4567
    - name: http-adminapi
      port: 9000
      targetPort: 9000
  type: ClusterIP
  selector:
    app: mysql-apiserver
