apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: mysql
  namespace: default
spec:
  rules:
  - services: ["mysql.default.svc.cluster.local"]
    methods: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: mysql
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/sectest-mysql-apiserver"
  roleRef:
    kind: ServiceRole
    name: "mysql"
