FROM ruby:2.5.1-alpine3.7

RUN apk --no-cache add \
      build-base \
      mysql-dev

RUN gem instal sinatra mysql2

RUN mkdir -p /app
WORKDIR /app
COPY mysql_api_server.rb mysql_api_server.rb

#ENV APP_ENV production
EXPOSE 4567

CMD ruby mysql_api_server.rb

