FROM ruby:2.5.1-alpine3.7

RUN gem install sinatra
RUN mkdir -p /app/views
WORKDIR /app
EXPOSE 4567
COPY front_end.rb front_end.rb
COPY index.erb views/index.erb
#ENV APP_ENV production

CMD ruby front_end.rb

